def error =
    let f = fun(x: Int) => x;
    f();
