exit status: 1

stdout = """
def foo: Bool -> #error = fun(_: Bool) => #error;
types of expressions:
10..34 = Bool -> #error
21..25 = Type
30..34 = Bool
types of patterns:
14..19 = Bool
"""

stderr = """
error: inexhaustive pattern match
  ┌─ tests/elab/errors/pattern_matching/inexhaustive_fun_lit.pion:1:15
  │
1 │ def foo = fun(false: Bool) => true;
  │               ^^^^^

aborting due to 1 previous error
"""
