def error = fun(x) => x;
