exit status: 1

stdout = """
def error: {x: Int, y: Bool} = {x = 1, y = false};
types of expressions:
12..32 = {x: Int, y: Bool}
15..16 = Int
19..24 = Bool
27..31 = <missing>
"""

stderr = """
error: duplicate field `x` in record type
  ┌─ tests/elab/errors/record_lit/duplicate_fields.pion:1:26
  │
1 │ def error = {x=1,y=false,x=true};
  │              -           ^ duplicate field
  │              │            
  │              first field

aborting due to 1 previous error
"""
